window.QUIZ_QUESTION_BANK={
xabcde:{title:"xABCDE Schema",questions:[
{id:"xabcde-x-001",question:"Was bedeutet das „x“ im xABCDE-Schema?",answers:["Exposition","Externe Verletzungen","Exsanguination","Extremitätenkontrolle"],correct:2,explanation:"Das „x“ steht für Exsanguination, also lebensbedrohliche Blutungen, die sofort gestoppt werden müssen."},
{id:"xabcde-a-001",question:"Was wird im A (Airway) überprüft?",answers:["Atemfrequenz","Atemtiefe","Atemwege und deren Freihaltung","Sauerstoffsättigung"],correct:2,explanation:"Im A geht es um die Sicherung der Atemwege, also frei oder verlegt."},
{id:"xabcde-b-001",question:"Was gehört primär zur Beurteilung von B (Breathing)?",answers:["Blutdruck messen","Atembewegung und Oxygenierung beurteilen","Pupillen kontrollieren","Blutzucker messen"],correct:1,explanation:"Bei B werden Atmung, Thoraxbewegung und Oxygenierung beurteilt."},
{id:"xabcde-c-001",question:"Was ist der Schwerpunkt bei C (Circulation)?",answers:["Bewusstseinslage","Kreislauf und Blutungen","Atemwegssicherung","Temperaturkontrolle"],correct:1,explanation:"C umfasst Kreislaufstatus, Puls, Blutdruck und Blutungen."},
{id:"xabcde-d-001",question:"Was wird bei D (Disability) beurteilt?",answers:["Atemmechanik","Neurologischer Status (z. B. AVPU, Pupillen)","Hautfarbe","Temperatur"],correct:1,explanation:"D steht für neurologische Beurteilung, häufig mit AVPU oder GCS."},
{id:"xabcde-e-001",question:"Wofür steht E (Exposure)?",answers:["Energieversorgung","Entzündung","Entkleiden und vollständige Untersuchung","Elektrolyte"],correct:2,explanation:"E bedeutet vollständige Inspektion des Patienten inklusive Entkleiden und Wärmeerhalt."}
]},
laborwerte:{title:"Laborwerte",questions:[
{id:"labor-niere-001",question:"Was gehört typischerweise zu den Nierenwerten im Labor?",answers:["CRP, Leukozyten, Thrombozyten","Kreatinin, Harnstoff, eGFR","Bilirubin, GOT, GPT","Natrium, Kalium, Calcium"],correct:1,explanation:"Zu den klassischen Nierenwerten gehören Kreatinin, Harnstoff und die eGFR zur Beurteilung der Nierenfunktion."},
{id:"labor-leber-001",question:"Welche Werte werden typischerweise zur Beurteilung der Leberfunktion bestimmt?",answers:["Kreatinin, Harnstoff, eGFR","Troponin, CK, CK-MB","GOT (AST), GPT (ALT), Gamma-GT, Bilirubin","CRP, Prokalzitonin, Leukozyten"],correct:2,explanation:"GOT, GPT und Gamma-GT zeigen Zellschädigung bzw. Cholestase an, Bilirubin gibt Hinweise auf die Leberfunktion."},
{id:"labor-crp-001",question:"Was beschreibt der Laborwert CRP?",answers:["Ein spezifischer Marker für Herzinfarkt","Ein Entzündungsparameter","Ein Nierenfunktionswert","Ein Gerinnungswert"],correct:1,explanation:"CRP ist ein unspezifischer Entzündungsmarker."}
]},
ekg:{title:"EKG lernen",questions:[
{id:"ekg-001",question:"Welche Aussage spricht am ehesten für einen Sinusrhythmus?",answers:["Keine P-Wellen sichtbar","Jede P-Welle wird von einem QRS-Komplex gefolgt","QRS-Komplex verbreitert","RR-Intervalle völlig unregelmäßig"],correct:1,explanation:"Beim Sinusrhythmus sind P-Wellen regelrecht vorhanden und jede P-Welle wird übergeleitet."},
{id:"ekg-002",question:"Welche Herzfrequenz gilt beim Erwachsenen im Buch als normofrequent?",answers:["40–60/min","50–100/min","60–120/min","70–110/min"],correct:1,explanation:"Im Buch wird der normofrequente Sinusrhythmus mit 50 bis 100 pro Minute angegeben."},
{id:"ekg-003",question:"Was repräsentiert die P-Welle?",answers:["Kammererregung","Vorhoferregung","Beginn der ST-Strecke","Kammerrepolarisation"],correct:1,explanation:"Die P-Welle steht für die intraatriale Erregungsausbreitung."},
{id:"ekg-004",question:"Was repräsentiert der QRS-Komplex?",answers:["Vorhofdepolarisation","AV-Überleitung","Intraventrikuläre Erregungsausbreitung","Kammerrepolarisation"],correct:2,explanation:"Der QRS-Komplex entspricht der Erregungsausbreitung in den Ventrikeln."},
{id:"ekg-005",question:"Wofür stehen ST-Strecke und T-Welle gemeinsam?",answers:["Vorhoferregung","Erregungsrückbildung in den Kammern","Atrioventrikuläre Überleitung","Lagetypeinstellung"],correct:1,explanation:"ST-Strecke und T-Welle repräsentieren die Kammerrepolarisation."},
{id:"ekg-006",question:"Wie lang ist die PQ-Zeit normalerweise?",answers:["0,04–0,08 s","0,08–0,10 s","0,12–0,20 s","0,22–0,30 s"],correct:2,explanation:"Die normale PQ-Zeit beträgt 0,12 bis 0,20 Sekunden."},
{id:"ekg-007",question:"Wie breit ist ein normaler QRS-Komplex typischerweise?",answers:["0,02–0,04 s","0,06–0,10 s","0,12–0,18 s","0,20–0,24 s"],correct:1,explanation:"Im Buch wird für den normalen QRS-Komplex eine Dauer von 0,06 bis 0,10 Sekunden angegeben."},
{id:"ekg-008",question:"In welcher Ableitung lässt sich die P-Welle meist am besten beurteilen?",answers:["aVR","Ableitung II","V6","I"],correct:1,explanation:"Für die P-Wellen-Analyse ist Ableitung II meist am hilfreichsten."},
{id:"ekg-009",question:"Was ist typisch für Vorhofflimmern?",answers:["Regelmäßige P-Wellen und konstante RR-Intervalle","Unregelmäßig unregelmäßiger Rhythmus ohne regelhafte P-Wellen","Breite QRS-Komplexe bei jedem Schlag","Immer ST-Hebungen in V1–V3"],correct:1,explanation:"Vorhofflimmern zeigt keine regelhaften P-Wellen und einen absolut unregelmäßigen Rhythmus."},
{id:"ekg-010",question:"Was bedeutet eine PQ-Zeit von mehr als 0,20 Sekunden bei 1:1-Überleitung?",answers:["AV-Block I°","AV-Block III°","WPW-Syndrom","Sinusknotenarrest"],correct:0,explanation:"Eine verlängerte PQ-Zeit bei weiterhin übergeleiteten P-Wellen entspricht einem AV-Block I°."},
{id:"ekg-011",question:"Was ist typisch für den AV-Block II° Typ Wenckebach?",answers:["Plötzlicher Ausfall eines QRS ohne vorherige PQ-Verlängerung","Progressive PQ-Verlängerung bis ein QRS ausfällt","Komplette AV-Dissoziation","Konstant verkürzte PQ-Zeit"],correct:1,explanation:"Beim Wenckebach-Typ verlängert sich die PQ-Zeit schrittweise, bis eine Überleitung ausfällt."},
{id:"ekg-012",question:"Welcher Befund passt am ehesten zu einem totalen AV-Block?",answers:["Regelmäßige P-Wellen, aber keinerlei Beziehung zu den QRS-Komplexen","Immer schmale QRS-Komplexe und Frequenz > 100/min","Nur ST-Hebungen in II, III und aVF","Fehlende T-Wellen in allen Ableitungen"],correct:0,explanation:"Der AV-Block III° zeigt eine komplette AV-Dissoziation."},
{id:"ekg-013",question:"Woran denkst du bei einer Tachykardie mit breitem QRS-Komplex zuerst?",answers:["Immer an Sinustachykardie","An eine ventrikuläre Genese, bis das Gegenteil bewiesen ist","An einen reinen Vorhofrhythmus","An einen SA-Block"],correct:1,explanation:"Ein breiter QRS bei Tachykardie ist ein wichtiges Warnsignal für ventrikuläre Rhythmusstörungen."},
{id:"ekg-014",question:"Welche Ableitungen repräsentieren die inferiore Wand?",answers:["I, aVL, V5, V6","V1–V4","II, III, aVF","V7–V9"],correct:2,explanation:"Die inferioren Ableitungen sind II, III und aVF."},
{id:"ekg-015",question:"Welche Ableitungen repräsentieren die hohe Seitenwand?",answers:["II, III, aVF","I und aVL","V1 und V2","V7 und V8"],correct:1,explanation:"I und aVL zeigen die laterale hohe Seitenwand."},
{id:"ekg-016",question:"Welche zusätzlichen Ableitungen werden zur direkten Beurteilung der posterioren Wand verwendet?",answers:["V1–V3","aVR, aVL, aVF","V7–V9","I, II, III"],correct:2,explanation:"Die strikt posteriore Hinterwand wird direkt mit V7 bis V9 abgeleitet."},
{id:"ekg-017",question:"Was ist ein typischer Hinweis auf einen kompletten Rechtsschenkelblock?",answers:["M-förmiger QRS in V1/V2","M-förmiger QRS in V5/V6","Verkürzte PQ-Zeit","Pathologisches Q in allen Brustwandableitungen"],correct:0,explanation:"Der komplette RSB zeigt typisch eine M-förmige Konfiguration in V1 und V2."},
{id:"ekg-018",question:"Was ist ein typischer Hinweis auf einen kompletten Linksschenkelblock?",answers:["M-förmiger QRS in V1/V2","M-förmiger QRS in V5/V6 sowie I und aVL","Nur eine einzelne tiefe S-Zacke in II","Immer normale T-Wellen"],correct:1,explanation:"Beim kompletten LSB findet sich die typische Deformierung linkspräkordial in V5/V6 und lateral in I/aVL."},
{id:"ekg-019",question:"Welche T-Wellen-Veränderung passt klassisch zur Hyperkaliämie?",answers:["Abgeflachte T-Wellen","Zeltförmig hohe T-Wellen","Nur terminal negative T-Wellen","Fehlende T-Wellen"],correct:1,explanation:"Hyperkaliämie führt typisch zu hohen, spitzen, zeltförmigen T-Wellen."},
{id:"ekg-020",question:"Was bedeutet eine verlängerte QT-Zeit grundsätzlich?",answers:["Verkürzte Kammererregung","Verlängerte gesamte intraventrikuläre Erregungsdauer","Vorhofleitungsstörung","Verkürzte AV-Überleitung"],correct:1,explanation:"Die QT-Zeit beschreibt die gesamte intraventrikuläre Erregungsdauer."},
{id:"ekg-021",question:"Was ist für ein P-dextroatriale typisch?",answers:["Doppelgipfelige verbreiterte P-Welle in II","Hohe spitze P-Welle über 0,25 mV","Fehlende P-Welle in II","Negative P-Welle in allen Ableitungen"],correct:1,explanation:"Das P-dextroatriale zeigt eine hohe, spitze P-Welle, besonders in II, III und aVF."},
{id:"ekg-022",question:"Was ist für ein P-sinistroatriale typisch?",answers:["Kurze spitze P-Welle","Verbreiterte, oft doppelgipfelige P-Welle","Verkürzte PQ-Zeit","Negative QRS-Komplexe"],correct:1,explanation:"Das P-sinistroatriale ist durch eine verbreiterte P-Welle mit typischer Morphologie gekennzeichnet."},
{id:"ekg-023",question:"Welche Reihenfolge passt zur strukturierten EKG-Befundung aus dem Buch?",answers:["QT, T, ST, QRS, P","Rhythmus/Frequenz/P/PQ, dann Lagetyp, Q-Zacken, RS-Zacken, ST/T","Nur Lagetyp und ST-Strecke","P-Welle, dann sofort Diagnose"],correct:1,explanation:"Die vorgeschlagene Systematik lautet Rhythmus/Frequenz/P/PQ, Lagetyp, Q-Zacken, RS-Zacken, ST-Strecke und T-Welle."},
{id:"ekg-024",question:"Welcher Befund spricht bei einer regelmäßigen schmalen Tachykardie eher für eine supraventrikuläre Ursache als für eine ventrikuläre?",answers:["Schmaler QRS-Komplex","AV-Dissoziation","Breite deformierte QRS-Komplexe","Capture Beats"],correct:0,explanation:"Schmale QRS-Komplexe sprechen eher für eine supraventrikuläre Tachykardie."},

{id:"ekg-img-001",type:"image",image:"assets/ekg/ekg-sinus.svg",imageAlt:"Stilisierter EKG-Streifen mit regelmäßigen P-Wellen vor jedem QRS-Komplex",question:"Welcher Rhythmus ist in diesem Bild am ehesten dargestellt?",answers:["Vorhofflimmern","Sinusrhythmus","AV-Block III°","Kammertachykardie"],correct:1,explanation:"Regelmäßige P-Wellen vor jedem QRS-Komplex sprechen hier für einen Sinusrhythmus."},
{id:"ekg-img-002",type:"image",image:"assets/ekg/ekg-afib.svg",imageAlt:"Stilisierter EKG-Streifen mit unregelmäßig unregelmäßigem RR-Abstand ohne geordnete P-Wellen",question:"Welcher Rhythmus ist hier am wahrscheinlichsten?",answers:["Sinusbradykardie","Vorhofflimmern","AV-junktionaler Rhythmus","Rechtsschenkelblock"],correct:1,explanation:"Das Bild zeigt einen unregelmäßig unregelmäßigen Rhythmus ohne regelhafte P-Wellen, typisch für Vorhofflimmern."},
{id:"ekg-img-003",type:"image",image:"assets/ekg/ekg-avblock1.svg",imageAlt:"Stilisierter EKG-Streifen mit erkennbarer P-Welle und verlängertem PQ-Intervall",question:"Welcher Hauptbefund passt am besten zu diesem Bild?",answers:["AV-Block I°","WPW-Syndrom","Vorhofflattern","AV-Block III°"],correct:0,explanation:"Die verlängerte PQ-Zeit bei weiter bestehender 1:1-Überleitung passt zu einem AV-Block I°."},
{id:"ekg-img-004",type:"image",image:"assets/ekg/ekg-rbbb.svg",imageAlt:"Stilisierte Brustwandableitung V1 mit rsR'-Muster und verbreitertem QRS-Komplex",question:"Welcher Befund ist hier am ehesten zu erkennen?",answers:["Kompletter Linksschenkelblock","Kompletter Rechtsschenkelblock","Linksanteriorer Hemiblock","Normales EKG"],correct:1,explanation:"Das rsR'- bzw. M-Muster in V1 spricht für einen Rechtsschenkelblock."},
{id:"ekg-img-005",type:"image",image:"assets/ekg/ekg-stemi-anterior.svg",imageAlt:"Stilisierte Ableitungen V2 bis V4 mit ST-Strecken-Hebungen",question:"Welche Diagnose passt am besten zu diesem EKG-Bild?",answers:["Anteroseptaler STEMI","Hyperkaliämie","Vorhofflimmern","Peripherer AV-Block III°"],correct:0,explanation:"ST-Hebungen in V2 bis V4 passen am ehesten zu einem anterioren bzw. anteroseptalen STEMI."},
{id:"ekg-img-006",type:"image",image:"assets/ekg/ekg-hyperkalemia.svg",imageAlt:"Stilisierter EKG-Streifen mit hohen, spitzen T-Wellen",question:"Welche Störung wird durch dieses EKG-Bild am ehesten nahegelegt?",answers:["Hypokaliämie","Hyperkaliämie","Perikarditis","Sinustachykardie"],correct:1,explanation:"Zeltförmig hohe T-Wellen sind klassisch für eine Hyperkaliämie. "}
]}

,
fachmodul4-ludwig:{title:"Dr. Maximilian Ludwig erläutert die essenziellen Abläufe der Allgemeinanästhesie im Schockraum",questions:[
{id:"fm4-001",question:"Aus welchen drei Hauptkomponenten setzt sich die Allgemeinanästhesie zusammen?",answers:["Sedierung, Intubation und Beatmung","Analgesie, Hypnose und Muskelrelaxation","Monitoring, Volumensubstitution und Lagerung","Präoxygenierung, Einleitung und Aufrechterhaltung"],correct:1,explanation:"Die klassische Trias der Allgemeinanästhesie besteht aus Analgesie, Hypnose und Muskelrelaxation."},
{id:"fm4-002",question:"Wie hoch ist laut Faustregel der maximal tolerable Abfall des systolischen Blutdrucks während der Narkoseeinleitung?",answers:["10 % des Ausgangswertes","20 % des Ausgangswertes","30 % des Ausgangswertes","50 % des Ausgangswertes"],correct:1,explanation:"Als Faustregel gilt ein maximal tolerabler Abfall des systolischen Blutdrucks um etwa 20 Prozent."},
{id:"fm4-003",question:"Welches Medikament kann eine neuromuskuläre Blockade durch Rocuronium sofort antagonisieren?",answers:["Sugammadex","Naloxon","Atropin","Akrinor"],correct:0,explanation:"Sugammadex kann Rocuronium gezielt antagonisieren."},
{id:"fm4-004",question:"Bei welcher Verletzung ist ein Wendl-Tubus kontraindiziert?",answers:["Isolierte Extremitätenfraktur","Verletzung des Gesichtsschädels oder der Schädelbasis","Stabile Halswirbelsäule","BMI über 30 kg/m²"],correct:1,explanation:"Bei Mittelgesichts- oder Schädelbasisverletzungen ist der nasale Atemweg kontraindiziert."},
{id:"fm4-005",question:"Welches Atemhubvolumen wird für eine lungenprotektive Beatmung im Schockraum empfohlen?",answers:["4–5 ml/kg IBW","6–8 ml/kg IBW","10–12 ml/kg IBW","Pauschal 500 ml für jeden Erwachsenen"],correct:1,explanation:"Empfohlen werden etwa 6 bis 8 ml pro Kilogramm ideales Körpergewicht."},
{id:"fm4-006",question:"Was ist die Ultima Ratio beim Cannot Intubate – Cannot Ventilate-Szenario?",answers:["Erneuter Versuch mit konventionellem Laryngoskop","Anlage einer Larynxmaske","Notfall-Koniotomie","Wechsel auf NIV"],correct:2,explanation:"Wenn weder Intubation noch Oxygenierung möglich sind, ist die Notfall-Koniotomie die Ultima Ratio."},
{id:"fm4-007",question:"Welches Kriterium gehört in der Berliner Polytrauma-Definition zusätzlich zu schweren Verletzungen von mindestens zwei Körperregionen?",answers:["Alter zwischen 18 und 45 Jahren","Azidose mit Base Excess ≤ -6,0","Systolischer Blutdruck genau 120 mmHg","GCS 15"],correct:1,explanation:"Eine relevante Azidose mit Base Excess ≤ -6,0 gehört zu den zusätzlichen Kriterien der Berliner Polytrauma-Definition."},
{id:"fm4-008",question:"Was ist das primäre Ziel der Schockraumphase Alpha?",answers:["Ganzkörper-CT durchführen","Initiale Stabilisierung und lebensrettende Sofortmaßnahmen nach xABCDE","Secondary Survey abschließen","Verlegung auf die Intensivstation"],correct:1,explanation:"In der Phase Alpha stehen Stabilisierung und lebensrettende Sofortmaßnahmen nach xABCDE im Vordergrund."},
{id:"fm4-009",question:"Wofür steht das V in den V2iSiOn-Alarmierungskriterien des nicht-traumatologischen Schockraums?",answers:["Vigilanzminderung","Volumenmangel","Vasopressor erhalten?","Ventilation fehlgeschlagen?"],correct:2,explanation:"Das V fragt nach bereits erhaltenen Vasopressoren."},
{id:"fm4-010",question:"Welche Situation ist eine absolute Kontraindikation für eine NIV-Beatmung?",answers:["Akute Exazerbation einer COPD","Gastrointestinale Blutung oder Ileus","Tachypnoe mit AF 25/min","Kardiogenes Lungenödem"],correct:1,explanation:"GI-Blutung oder Ileus gelten als absolute Kontraindikationen für NIV."},
{id:"fm4-011",question:"Welche drei Parameter bilden den qSOFA-Score?",answers:["Herzfrequenz, Temperatur, Leukozyten","Atemfrequenz ≥22/min, Vigilanzstörung, systolischer Blutdruck ≤100 mmHg","Sauerstoffsättigung, Urinausscheidung, Laktat","AF >30/min, HF >120/min, Base Excess < -6"],correct:1,explanation:"Der qSOFA besteht aus Atemfrequenz, Vigilanz und systolischem Blutdruck."},
{id:"fm4-012",question:"Ab wie vielen erfüllten qSOFA-Kriterien besteht bei passender Infektionskonstellation ein Sepsisverdacht?",answers:["Ab 1 Kriterium","Ab 2 Kriterien","Nur bei allen 3 Kriterien","Erst nach 24 Stunden"],correct:1,explanation:"Ab zwei erfüllten qSOFA-Kriterien besteht ein relevanter Sepsisverdacht."},
{id:"fm4-013",question:"Welche Maßnahme gehört zum Hour-1-Bundle der Surviving Sepsis Campaign?",answers:["Unabhängig von der Sättigung sofort intubieren","1000 ml Kolloide in 10 Minuten geben","Laktat messen und bei initial >2 mmol/l erneut kontrollieren","Diuretika zur Nierenstimulation geben"],correct:2,explanation:"Die frühe Laktatmessung inklusive Re-Evaluation ist Teil des Hour-1-Bundles."},
{id:"fm4-014",question:"In welcher Phase des Schockraummanagements erfolgt typischerweise der Secondary Survey?",answers:["Phase Alpha","Phase Bravo","Phase Charlie","Erst auf der Intensivstation"],correct:1,explanation:"Der Secondary Survey erfolgt nach der initialen Stabilisierung typischerweise in Phase Bravo."},
{id:"fm4-015",question:"Welchen Effekt hat eine Körperkerntemperatur unter 35 °C beim Traumapatienten auf die Gerinnung?",answers:["Die Gerinnung verbessert sich durch Vasokonstriktion","Die Aktivität der Gerinnungsfaktoren sinkt um etwa 10 % pro Grad","Sie hat keinen messbaren Einfluss","Das Risiko einer Hyperkaliämie sinkt"],correct:1,explanation:"Hypothermie verschlechtert die Gerinnung, grob um etwa 10 Prozent pro Grad unter 35 °C."},
{id:"fm4-016",question:"Wie stark wirkt Sufentanil ungefähr im Vergleich zu Morphin?",answers:["10-mal so stark","100-mal so stark","500- bis 1000-mal so stark","Schwächer als Morphin"],correct:2,explanation:"Sufentanil ist deutlich potenter und liegt ungefähr 500- bis 1000-mal über Morphin."},
{id:"fm4-017",question:"Welches Hypnotikum wird typischerweise mit 1,5 bis 2,5 mg/kgKG eingeleitet und wirkt primär am GABA-A-Rezeptor?",answers:["Thiopental","Propofol","Ketamin","Succinylcholin"],correct:1,explanation:"Propofol wirkt primär über den GABA-A-Rezeptor und wird häufig in diesem Dosisbereich verwendet."},
{id:"fm4-018",question:"Was ist eine klassische Kontraindikation für Succinylcholin?",answers:["Hyperkaliämie","Hypotonie","Adipositas","Maligne Hypotonie"],correct:0,explanation:"Hyperkaliämie ist eine klassische Kontraindikation für Succinylcholin."},
{id:"fm4-019",question:"Welcher Mallampati-Grad zeigt nur noch den harten Gaumen, ohne Sicht auf Uvula und weichen Gaumen?",answers:["Klasse 1","Klasse 2","Klasse 3","Klasse 4"],correct:3,explanation:"Mallampati IV zeigt nur den harten Gaumen und spricht für einen schwierigen Atemweg."},
{id:"fm4-020",question:"Welcher Beatmungsparameter wird bei NIV begrenzt, um eine Magenüberblähung zu vermeiden?",answers:["Atemhubvolumen auf maximal 300 ml","FiO2 auf maximal 0,5","Spitzendruck auf maximal etwa 25 cmH2O","Atemfrequenz auf maximal 15/min"],correct:2,explanation:"Der Spitzendruck wird begrenzt, orientiert am ösophagealen Verschlussdruck um etwa 25 cmH2O."},
{id:"fm4-021",question:"Welche Aussage zum Wendl-Tubus ist korrekt?",answers:["Er schützt sicher vor Aspiration","Er wird oral eingeführt","Er ist bei Schädelbasisverletzung kontraindiziert","Er wird direkt an das Beatmungsgerät angeschlossen"],correct:2,explanation:"Der Wendl-Tubus ist ein nasopharyngealer Atemweg und bei Schädelbasisverletzung kontraindiziert."},
{id:"fm4-022",question:"Wie groß ist der maximale Durchfluss einer G14-Venenverweilkanüle ungefähr?",answers:["Ca. 3 l/h","Ca. 6 l/h","Ca. 12 l/h","Ca. 20 l/h"],correct:3,explanation:"Eine großlumige G14-Kanüle erlaubt sehr hohe Durchflussraten bis ungefähr 20 Liter pro Stunde."},
{id:"fm4-023",question:"Was besagt das 10-für-10-Prinzip im CRM?",answers:["10 Minuten Behandlung für 10 Euro Materialkosten","10 Sekunden Zeit nehmen, um die nächsten 10 Minuten zu planen","10 Teammitglieder für 10 Betten","10 Liter Sauerstoff für 10 Minuten Präoxygenierung"],correct:1,explanation:"Das 10-für-10-Prinzip meint eine kurze Pause, um die nächsten zehn Minuten strukturiert zu planen."},
{id:"fm4-024",question:"Welche der folgenden Aussagen beschreibt eine RSI-Einleitung am treffendsten?",answers:["Langsame Medikamentengabe mit Zwischenbeatmung über mehrere Minuten","Rasche Sequenz aus Hypnotikum und Relaxans zur schnellen Atemwegssicherung","Ausschließlich Analgesie ohne Hypnose","Nur bei stabilem Spontanatmer sinnvoll"],correct:1,explanation:"Die RSI ist eine Rapid Sequence Induction mit zügiger Einleitung zur schnellen Atemwegssicherung und Aspirationsprophylaxe."},
{id:"fm4-025",question:"Welche Priorität hat das xABCDE-Schema im Schockraum?",answers:["Erst die vollständige Diagnostik, dann die Reihenfolge","Prioritäten strikt nach lebensbedrohlichen Problemen von x bis E abarbeiten","Immer zuerst Disability, weil der GCS schnell erhoben ist","Exposure erst vor Airway"],correct:1,explanation:"xABCDE priorisiert lebensbedrohliche Probleme in fester Reihenfolge, damit keine vitale Bedrohung übersehen wird."}
]}

};
