window.QUIZ_QUESTION_BANK={
xabcde:{title:"xABCDE Schema",questions:[
{id:"xabcde-x-001",question:"Was bedeutet das „x“ im xABCDE-Schema?",answers:["Exposition","Externe Verletzungen","Exsanguination","Extremitätenkontrolle"],correct:2,explanation:"Das „x“ steht für Exsanguination, also lebensbedrohliche Blutungen, die sofort gestoppt werden müssen."},
{id:"xabcde-a-001",question:"Was wird im A (Airway) überprüft?",answers:["Atemfrequenz","Atemtiefe","Atemwege und deren Freihaltung","Sauerstoffsättigung"],correct:2,explanation:"Im A geht es um die Sicherung der Atemwege, also frei oder verlegt."},
{id:"xabcde-b-001",question:"Was gehört primär zur Beurteilung von B (Breathing)?",answers:["Blutdruck messen","Atembewegung und Oxygenierung beurteilen","Pupillen kontrollieren","Blutzucker messen"],correct:1,explanation:"Bei B werden Atmung, Thoraxbewegung und Oxygenierung beurteilt."},
{id:"xabcde-c-001",question:"Was ist der Schwerpunkt bei C (Circulation)?",answers:["Bewusstseinslage","Kreislauf und Blutungen","Atemwegssicherung","Temperaturkontrolle"],correct:1,explanation:"C umfasst Kreislaufstatus, Puls, Blutdruck und Blutungen."},
{id:"xabcde-d-001",question:"Was wird bei D (Disability) beurteilt?",answers:["Atemmechanik","Neurologischer Status (z. B. AVPU, Pupillen)","Hautfarbe","Temperatur"],correct:1,explanation:"D steht für neurologische Beurteilung, häufig mit AVPU oder GCS."},
{id:"xabcde-e-001",question:"Wofür steht E (Exposure)?",answers:["Energieversorgung","Entzündung","Entkleiden und vollständige Untersuchung","Elektrolyte"],correct:2,explanation:"E bedeutet vollständige Inspektion des Patienten inklusive Entkleiden und Wärmeerhalt."}
]},
laborwerte:{title:"Laborwerte",questions:[
{id:"labor-niere-001",question:"Was gehört typischerweise zu den Nierenwerten im Labor?",answers:["CRP, Leukozyten, Thrombozyten","Kreatinin, Harnstoff, eGFR","Bilirubin, GOT, GPT","Natrium, Kalium, Calcium"],correct:1,explanation:"Zu den klassischen Nierenwerten gehören Kreatinin, Harnstoff und die eGFR zur Beurteilung der Nierenfunktion."},
{id:"labor-leber-001",question:"Welche Werte werden typischerweise zur Beurteilung der Leberfunktion bestimmt?",answers:["Kreatinin, Harnstoff, eGFR","Troponin, CK, CK-MB","GOT (AST), GPT (ALT), Gamma-GT, Bilirubin","CRP, Prokalzitonin, Leukozyten"],correct:2,explanation:"GOT, GPT und Gamma-GT zeigen Zellschädigung bzw. Cholestase an, Bilirubin gibt Hinweise auf die Leberfunktion."},
{id:"labor-crp-001",question:"Was beschreibt der Laborwert CRP?",answers:["Ein spezifischer Marker für Herzinfarkt","Ein Entzündungsparameter","Ein Nierenfunktionswert","Ein Gerinnungswert"],correct:1,explanation:"CRP ist ein unspezifischer Entzündungsmarker."}
]},
ekg:{title:"EKG lernen",questions:[
{id:"ekg-001",question:"Welche Aussage spricht am ehesten für einen Sinusrhythmus?",answers:["Keine P-Wellen sichtbar","Jede P-Welle wird von einem QRS-Komplex gefolgt","QRS-Komplex verbreitert","RR-Intervalle völlig unregelmäßig"],correct:1,explanation:"Beim Sinusrhythmus sind P-Wellen regelrecht vorhanden und jede P-Welle wird übergeleitet."},
{id:"ekg-002",question:"Welche Herzfrequenz gilt beim Erwachsenen im Buch als normofrequent?",answers:["40–60/min","50–100/min","60–120/min","70–110/min"],correct:1,explanation:"Im Buch wird der normofrequente Sinusrhythmus mit 50 bis 100 pro Minute angegeben."},
{id:"ekg-003",question:"Was repräsentiert die P-Welle?",answers:["Kammererregung","Vorhoferregung","Beginn der ST-Strecke","Kammerrepolarisation"],correct:1,explanation:"Die P-Welle steht für die intraatriale Erregungsausbreitung."},
{id:"ekg-004",question:"Was repräsentiert der QRS-Komplex?",answers:["Vorhofdepolarisation","AV-Überleitung","Intraventrikuläre Erregungsausbreitung","Kammerrepolarisation"],correct:2,explanation:"Der QRS-Komplex entspricht der Erregungsausbreitung in den Ventrikeln."},
{id:"ekg-005",question:"Wofür stehen ST-Strecke und T-Welle gemeinsam?",answers:["Vorhoferregung","Erregungsrückbildung in den Kammern","Atrioventrikuläre Überleitung","Lagetypeinstellung"],correct:1,explanation:"ST-Strecke und T-Welle repräsentieren die Kammerrepolarisation."},
{id:"ekg-006",question:"Wie lang ist die PQ-Zeit normalerweise?",answers:["0,04–0,08 s","0,08–0,10 s","0,12–0,20 s","0,22–0,30 s"],correct:2,explanation:"Die normale PQ-Zeit beträgt 0,12 bis 0,20 Sekunden."},
{id:"ekg-007",question:"Wie breit ist ein normaler QRS-Komplex typischerweise?",answers:["0,02–0,04 s","0,06–0,10 s","0,12–0,18 s","0,20–0,24 s"],correct:1,explanation:"Im Buch wird für den normalen QRS-Komplex eine Dauer von 0,06 bis 0,10 Sekunden angegeben."},
{id:"ekg-008",question:"In welcher Ableitung lässt sich die P-Welle meist am besten beurteilen?",answers:["aVR","Ableitung II","V6","I"],correct:1,explanation:"Für die P-Wellen-Analyse ist Ableitung II meist am hilfreichsten."},
{id:"ekg-009",question:"Was ist typisch für Vorhofflimmern?",answers:["Regelmäßige P-Wellen und konstante RR-Intervalle","Unregelmäßig unregelmäßiger Rhythmus ohne regelhafte P-Wellen","Breite QRS-Komplexe bei jedem Schlag","Immer ST-Hebungen in V1–V3"],correct:1,explanation:"Vorhofflimmern zeigt keine regelhaften P-Wellen und einen absolut unregelmäßigen Rhythmus."},
{id:"ekg-010",question:"Was bedeutet eine PQ-Zeit von mehr als 0,20 Sekunden bei 1:1-Überleitung?",answers:["AV-Block I°","AV-Block III°","WPW-Syndrom","Sinusknotenarrest"],correct:0,explanation:"Eine verlängerte PQ-Zeit bei weiterhin übergeleiteten P-Wellen entspricht einem AV-Block I°."},
{id:"ekg-011",question:"Was ist typisch für den AV-Block II° Typ Wenckebach?",answers:["Plötzlicher Ausfall eines QRS ohne vorherige PQ-Verlängerung","Progressive PQ-Verlängerung bis ein QRS ausfällt","Komplette AV-Dissoziation","Konstant verkürzte PQ-Zeit"],correct:1,explanation:"Beim Wenckebach-Typ verlängert sich die PQ-Zeit schrittweise, bis eine Überleitung ausfällt."},
{id:"ekg-012",question:"Welcher Befund passt am ehesten zu einem totalen AV-Block?",answers:["Regelmäßige P-Wellen, aber keinerlei Beziehung zu den QRS-Komplexen","Immer schmale QRS-Komplexe und Frequenz > 100/min","Nur ST-Hebungen in II, III und aVF","Fehlende T-Wellen in allen Ableitungen"],correct:0,explanation:"Der AV-Block III° zeigt eine komplette AV-Dissoziation."},
{id:"ekg-013",question:"Woran denkst du bei einer Tachykardie mit breitem QRS-Komplex zuerst?",answers:["Immer an Sinustachykardie","An eine ventrikuläre Genese, bis das Gegenteil bewiesen ist","An einen reinen Vorhofrhythmus","An einen SA-Block"],correct:1,explanation:"Ein breiter QRS bei Tachykardie ist ein wichtiges Warnsignal für ventrikuläre Rhythmusstörungen."},
{id:"ekg-014",question:"Welche Ableitungen repräsentieren die inferiore Wand?",answers:["I, aVL, V5, V6","V1–V4","II, III, aVF","V7–V9"],correct:2,explanation:"Die inferioren Ableitungen sind II, III und aVF."},
{id:"ekg-015",question:"Welche Ableitungen repräsentieren die hohe Seitenwand?",answers:["II, III, aVF","I und aVL","V1 und V2","V7 und V8"],correct:1,explanation:"I und aVL zeigen die laterale hohe Seitenwand."},
{id:"ekg-016",question:"Welche zusätzlichen Ableitungen werden zur direkten Beurteilung der posterioren Wand verwendet?",answers:["V1–V3","aVR, aVL, aVF","V7–V9","I, II, III"],correct:2,explanation:"Die strikt posteriore Hinterwand wird direkt mit V7 bis V9 abgeleitet."},
{id:"ekg-017",question:"Was ist ein typischer Hinweis auf einen kompletten Rechtsschenkelblock?",answers:["M-förmiger QRS in V1/V2","M-förmiger QRS in V5/V6","Verkürzte PQ-Zeit","Pathologisches Q in allen Brustwandableitungen"],correct:0,explanation:"Der komplette RSB zeigt typisch eine M-förmige Konfiguration in V1 und V2."},
{id:"ekg-018",question:"Was ist ein typischer Hinweis auf einen kompletten Linksschenkelblock?",answers:["M-förmiger QRS in V1/V2","M-förmiger QRS in V5/V6 sowie I und aVL","Nur eine einzelne tiefe S-Zacke in II","Immer normale T-Wellen"],correct:1,explanation:"Beim kompletten LSB findet sich die typische Deformierung linkspräkordial in V5/V6 und lateral in I/aVL."},
{id:"ekg-019",question:"Welche T-Wellen-Veränderung passt klassisch zur Hyperkaliämie?",answers:["Abgeflachte T-Wellen","Zeltförmig hohe T-Wellen","Nur terminal negative T-Wellen","Fehlende T-Wellen"],correct:1,explanation:"Hyperkaliämie führt typisch zu hohen, spitzen, zeltförmigen T-Wellen."},
{id:"ekg-020",question:"Was bedeutet eine verlängerte QT-Zeit grundsätzlich?",answers:["Verkürzte Kammererregung","Verlängerte gesamte intraventrikuläre Erregungsdauer","Vorhofleitungsstörung","Verkürzte AV-Überleitung"],correct:1,explanation:"Die QT-Zeit beschreibt die gesamte intraventrikuläre Erregungsdauer."},
{id:"ekg-021",question:"Was ist für ein P-dextroatriale typisch?",answers:["Doppelgipfelige verbreiterte P-Welle in II","Hohe spitze P-Welle über 0,25 mV","Fehlende P-Welle in II","Negative P-Welle in allen Ableitungen"],correct:1,explanation:"Das P-dextroatriale zeigt eine hohe, spitze P-Welle, besonders in II, III und aVF."},
{id:"ekg-022",question:"Was ist für ein P-sinistroatriale typisch?",answers:["Kurze spitze P-Welle","Verbreiterte, oft doppelgipfelige P-Welle","Verkürzte PQ-Zeit","Negative QRS-Komplexe"],correct:1,explanation:"Das P-sinistroatriale ist durch eine verbreiterte P-Welle mit typischer Morphologie gekennzeichnet."},
{id:"ekg-023",question:"Welche Reihenfolge passt zur strukturierten EKG-Befundung aus dem Buch?",answers:["QT, T, ST, QRS, P","Rhythmus/Frequenz/P/PQ, dann Lagetyp, Q-Zacken, RS-Zacken, ST/T","Nur Lagetyp und ST-Strecke","P-Welle, dann sofort Diagnose"],correct:1,explanation:"Die vorgeschlagene Systematik lautet Rhythmus/Frequenz/P/PQ, Lagetyp, Q-Zacken, RS-Zacken, ST-Strecke und T-Welle."},
{id:"ekg-024",question:"Welcher Befund spricht bei einer regelmäßigen schmalen Tachykardie eher für eine supraventrikuläre Ursache als für eine ventrikuläre?",answers:["Schmaler QRS-Komplex","AV-Dissoziation","Breite deformierte QRS-Komplexe","Capture Beats"],correct:0,explanation:"Schmale QRS-Komplexe sprechen eher für eine supraventrikuläre Tachykardie."},

{id:"ekg-img-001",type:"image",image:"assets/ekg/ekg-sinus.svg",imageAlt:"Stilisierter EKG-Streifen mit regelmäßigen P-Wellen vor jedem QRS-Komplex",question:"Welcher Rhythmus ist in diesem Bild am ehesten dargestellt?",answers:["Vorhofflimmern","Sinusrhythmus","AV-Block III°","Kammertachykardie"],correct:1,explanation:"Regelmäßige P-Wellen vor jedem QRS-Komplex sprechen hier für einen Sinusrhythmus."},
{id:"ekg-img-002",type:"image",image:"assets/ekg/ekg-afib.svg",imageAlt:"Stilisierter EKG-Streifen mit unregelmäßig unregelmäßigem RR-Abstand ohne geordnete P-Wellen",question:"Welcher Rhythmus ist hier am wahrscheinlichsten?",answers:["Sinusbradykardie","Vorhofflimmern","AV-junktionaler Rhythmus","Rechtsschenkelblock"],correct:1,explanation:"Das Bild zeigt einen unregelmäßig unregelmäßigen Rhythmus ohne regelhafte P-Wellen, typisch für Vorhofflimmern."},
{id:"ekg-img-003",type:"image",image:"assets/ekg/ekg-avblock1.svg",imageAlt:"Stilisierter EKG-Streifen mit erkennbarer P-Welle und verlängertem PQ-Intervall",question:"Welcher Hauptbefund passt am besten zu diesem Bild?",answers:["AV-Block I°","WPW-Syndrom","Vorhofflattern","AV-Block III°"],correct:0,explanation:"Die verlängerte PQ-Zeit bei weiter bestehender 1:1-Überleitung passt zu einem AV-Block I°."},
{id:"ekg-img-004",type:"image",image:"assets/ekg/ekg-rbbb.svg",imageAlt:"Stilisierte Brustwandableitung V1 mit rsR'-Muster und verbreitertem QRS-Komplex",question:"Welcher Befund ist hier am ehesten zu erkennen?",answers:["Kompletter Linksschenkelblock","Kompletter Rechtsschenkelblock","Linksanteriorer Hemiblock","Normales EKG"],correct:1,explanation:"Das rsR'- bzw. M-Muster in V1 spricht für einen Rechtsschenkelblock."},
{id:"ekg-img-005",type:"image",image:"assets/ekg/ekg-stemi-anterior.svg",imageAlt:"Stilisierte Ableitungen V2 bis V4 mit ST-Strecken-Hebungen",question:"Welche Diagnose passt am besten zu diesem EKG-Bild?",answers:["Anteroseptaler STEMI","Hyperkaliämie","Vorhofflimmern","Peripherer AV-Block III°"],correct:0,explanation:"ST-Hebungen in V2 bis V4 passen am ehesten zu einem anterioren bzw. anteroseptalen STEMI."},
{id:"ekg-img-006",type:"image",image:"assets/ekg/ekg-hyperkalemia.svg",imageAlt:"Stilisierter EKG-Streifen mit hohen, spitzen T-Wellen",question:"Welche Störung wird durch dieses EKG-Bild am ehesten nahegelegt?",answers:["Hypokaliämie","Hyperkaliämie","Perikarditis","Sinustachykardie"],correct:1,explanation:"Zeltförmig hohe T-Wellen sind klassisch für eine Hyperkaliämie. "}
]}

,
fachmodul4:{title:"Dr. Maximilian Ludwig erläutert die essenziellen Abläufe der Allgemeinanästhesie im Schockraum",questions:[
{id:"fm4-001",question:"Aus welchen drei Hauptkomponenten setzt sich die Allgemeinanästhesie (Narkose) zusammen?",answers:["Sedierung, Intubation und Beatmung","Analgesie, Hypnose und Muskelrelaxation","Monitoring, Volumensubstitution und Lagerung","Präoxygenierung, Einleitung und Aufrechterhaltung"],correct:1,explanation:"Die Allgemeinanästhesie beruht klassisch auf Analgesie, Hypnose und Muskelrelaxation."},
{id:"fm4-002",question:"Wie hoch ist laut den Faustregeln der maximal tolerable Abfall des systolischen Blutdrucks während der Narkoseeinleitung?",answers:["Maximal 10 % des Ausgangswertes","Maximal 20 % des Ausgangswertes","Maximal 30 % des Ausgangswertes","Maximal 50 % des Ausgangswertes"],correct:1,explanation:"Ein systolischer Blutdruckabfall bis etwa 20 % des Ausgangswertes gilt als tolerabel."},
{id:"fm4-003",question:"Welches Medikament kann zur sofortigen Aufhebung einer neuromuskulären Blockade durch Rocuronium eingesetzt werden?",answers:["Sugammadex","Naloxon","Atropin","Akrinor"],correct:0,explanation:"Sugammadex antagonisiert Rocuronium gezielt und rasch."},
{id:"fm4-004",question:"Bei welcher Patientengruppe ist die Einlage eines Wendl-Tubus kontraindiziert?",answers:["Bei isolierten Extremitätenfrakturen","Bei Verletzungen des Gesichtsschädels oder der Schädelbasis","Bei stabiler Halswirbelsäule","Bei BMI über 30 kg/m²"],correct:1,explanation:"Bei Verdacht auf Mittelgesichts- oder Schädelbasisverletzungen ist der nasale Zugang kontraindiziert."},
{id:"fm4-005",question:"Welches Atemhubvolumen wird für eine lungenprotektive Beatmung im Schockraum empfohlen?",answers:["4–5 ml/kgKG IBW","6–8 ml/kgKG IBW","10–12 ml/kgKG IBW","Pauschal 500 ml"],correct:1,explanation:"Lungenprotektive Beatmung erfolgt mit etwa 6 bis 8 ml/kg idealem Körpergewicht."},
{id:"fm4-006",question:"Was ist die Ultima Ratio bei einem Cannot Intubate – Cannot Ventilate-Szenario?",answers:["Erneuter Versuch mit konventionellem Laryngoskop","Anlage einer Larynxmaske","Notfall-Koniotomie","Wechsel auf NIV"],correct:2,explanation:"Wenn weder Intubation noch Oxygenierung möglich sind, ist die Notfall-Koniotomie die letzte lebensrettende Option."},
{id:"fm4-007",question:"Welches Kriterium gehört zusätzlich zu schweren Verletzungen von mindestens zwei Körperregionen zur Berliner Polytrauma-Definition?",answers:["Alter zwischen 18 und 45 Jahren","Azidose mit Base Excess ≤ -6,0","Systolischer Blutdruck genau 120 mmHg","GCS 15"],correct:1,explanation:"Eine relevante Azidose zählt zu den zusätzlichen physiologischen Kriterien der Polytrauma-Definition."},
{id:"fm4-008",question:"Was ist das primäre Ziel der Schockraumphase Alpha (Minuten 0–3)?",answers:["Komplettes Ganzkörper-CT","Initiale Stabilisierung und lebensrettende Sofortmaßnahmen nach xABCDE","Abschluss der Secondary Survey","Verlegung auf Intensivstation"],correct:1,explanation:"In der Alpha-Phase stehen schnelle Stabilisierung und lebensrettende Erstmaßnahmen im Vordergrund."},
{id:"fm4-009",question:"Wofür steht das V in den V2iSiOn-Alarmierungskriterien für den nicht-traumatologischen Schockraum?",answers:["Vigilanzminderung","Volumenmangel","Vasopressor erhalten?","Ventilation fehlgeschlagen?"],correct:2,explanation:"Das V fragt nach bereits erfolgter Vasopressorgabe."},
{id:"fm4-010",question:"Welche Situation ist eine absolute Kontraindikation für eine NIV-Beatmung?",answers:["Akute Exazerbation einer COPD","Gastrointestinale Blutung oder Ileus","Tachypnoe 25/min","Kardiogenes Lungenödem"],correct:1,explanation:"Bei gastrointestinaler Blutung oder Ileus besteht ein hohes Aspirations- und Komplikationsrisiko unter NIV."},
{id:"fm4-011",question:"Welche drei Parameter bilden den qSOFA-Score?",answers:["Herzfrequenz, Temperatur, Leukozyten","Atemfrequenz ≥22/min, Vigilanzminderung, systolischer Blutdruck ≤100 mmHg","Sauerstoffsättigung, Urinausscheidung, Laktat","Atemfrequenz >30/min, Herzfrequenz >120/min, Base Excess < -6"],correct:1,explanation:"Der qSOFA besteht aus Atemfrequenz, Blutdruck und Vigilanz."},
{id:"fm4-012",question:"Ab wie vielen erfüllten qSOFA-Kriterien besteht bei Infektionshinweis ein Sepsisverdacht?",answers:["Ab 1 Kriterium","Ab 2 Kriterien","Nur bei allen 3 Kriterien","Erst nach 24 Stunden"],correct:1,explanation:"Ein qSOFA von 2 oder mehr bei vermuteter Infektion spricht für erhöhtes Sepsisrisiko."},
{id:"fm4-013",question:"Was gehört zum Hour-1 Bundle der Sepsistherapie?",answers:["Sofortige Intubation unabhängig von der Sättigung","1000 ml Kolloide in 10 Minuten","Messung des Laktatwerts und Re-Evaluation bei initial >2 mmol/l","Diuretika zur Nierenstimulation"],correct:2,explanation:"Die frühe Laktatbestimmung ist eine Kernmaßnahme der initialen Sepsisbehandlung."},
{id:"fm4-014",question:"In welcher Phase des Schockraummanagements erfolgt der Secondary Survey?",answers:["Phase Alpha","Phase Bravo","Phase Charlie","Erst auf Intensivstation"],correct:1,explanation:"Der Secondary Survey erfolgt typischerweise in der Bravo-Phase nach der initialen Stabilisierung."},
{id:"fm4-015",question:"Welchen Effekt hat eine Körperkerntemperatur unter 35 °C beim Traumapatienten auf die Gerinnung?",answers:["Die Gerinnungsaktivität verbessert sich","Die Aktivität der Gerinnungsfaktoren sinkt um etwa 10 % pro Grad","Kein messbarer Einfluss","Das Hyperkaliämierisiko sinkt"],correct:1,explanation:"Hypothermie verschlechtert die Gerinnung deutlich, ungefähr 10 % Aktivitätsverlust pro Grad unter 35 °C."},
{id:"fm4-016",question:"Wie stark wirkt Sufentanil ungefähr im Vergleich zu Morphin?",answers:["Etwa 10-mal so stark","Etwa 100-mal so stark","Etwa 500- bis 1000-mal so stark","Sufentanil ist schwächer als Morphin"],correct:2,explanation:"Sufentanil ist im Vergleich zu Morphin um ein Vielfaches potenter."},
{id:"fm4-017",question:"Welches Hypnotikum wirkt primär über den GABA-A-Rezeptor und wird mit etwa 1,5–2,5 mg/kgKG dosiert?",answers:["Thiopental","Propofol","Ketamin","Succinylcholin"],correct:1,explanation:"Propofol wird zur Einleitung typischerweise mit 1,5 bis 2,5 mg/kgKG verwendet."},
{id:"fm4-018",question:"Was ist eine klassische Kontraindikation für Succinylcholin?",answers:["Hyperkaliämie","Hypotonie","Adipositas","Maligne Hypotonie"],correct:0,explanation:"Succinylcholin kann Kalium ansteigen lassen und ist daher bei Hyperkaliämie problematisch."},
{id:"fm4-019",question:"Welcher Mallampati-Grad beschreibt eine Sichtbarkeit nur noch des harten Gaumens?",answers:["Klasse 1","Klasse 2","Klasse 3","Klasse 4"],correct:3,explanation:"Mallampati IV bedeutet, dass nur der harte Gaumen sichtbar ist."},
{id:"fm4-020",question:"Welcher Beatmungsparameter wird bei NIV zur Vermeidung einer Magenüberblähung begrenzt?",answers:["Atemhubvolumen auf 300 ml","FiO2 auf 0,5","Spitzendruck auf maximal 25 cmH2O","Atemfrequenz auf 15/min"],correct:2,explanation:"Der Spitzendruck sollte unter dem ösophagealen Verschlussdruck bleiben, typischerweise etwa 25 cmH2O."},
{id:"fm4-021",question:"Welche Aussage zum Wendl-Tubus ist korrekt?",answers:["Er schützt sicher vor Aspiration","Er wird durch den Mund eingeführt","Er ist bei Verletzungen der Schädelbasis kontraindiziert","Er erlaubt direkte Konnektion an das Beatmungsgerät"],correct:2,explanation:"Der Wendl-Tubus ist ein nasopharyngealer Tubus und bei Schädelbasisverletzungen kontraindiziert."},
{id:"fm4-022",question:"Wie groß ist der maximale Durchfluss pro Stunde bei einer orange-braunen Venenverweilkanüle G14 ungefähr?",answers:["Ca. 3 l/h","Ca. 6 l/h","Ca. 12 l/h","Ca. 20 l/h"],correct:3,explanation:"Eine großlumige G14-Kanüle erlaubt sehr hohe Durchflussraten, ungefähr 20 Liter pro Stunde."},
{id:"fm4-023",question:"Was besagt das 10-für-10-Prinzip im CRM?",answers:["10 Minuten Behandlung für 10 Euro Materialkosten","10 Sekunden nehmen, um die nächsten 10 Minuten zu planen","10 Teammitglieder für 10 Betten","10 Liter Sauerstoff für 10 Minuten Präoxygenierung"],correct:1,explanation:"Das 10-für-10-Prinzip bedeutet kurze bewusste Planungspausen, um die nächsten Schritte zu strukturieren."},
{id:"fm4-024",question:"Welcher Wert ist Teil des qSOFA, aber kein klassischer Laborwert?",answers:["Leukozyten","Laktat","Vigilanz bzw. GCS < 15","CRP"],correct:2,explanation:"Der qSOFA nutzt klinische Parameter, darunter Vigilanzminderung bzw. GCS unter 15."},
{id:"fm4-025",question:"Welche Aussage beschreibt RSI am treffendsten?",answers:["Langsame stufenweise Einleitung mit erhaltener Spontanatmung","Rasche Einleitung mit dem Ziel einer schnellen Atemwegssicherung und minimiertem Aspirationsrisiko","Ausschließlich regionale Anästhesie im Schockraum","Beatmung ohne Medikamente"],correct:1,explanation:"Die Rapid Sequence Induction dient der schnellen und kontrollierten Atemwegssicherung bei Aspirationsgefahr."}
]}

};
